// -------------------------------------------------------
// <auto-generated>
//    This file is generated by wshcmx/net project. Do not edit manually.
//    Generated on: 2026-05-14 21:50:11
// <auto-generated />
// -------------------------------------------------------

declare namespace wshcmx {
  namespace Net {
    type KeyValuePair<K, V> = { Key: K; Value: V };

    export abstract class ProcessHelper {
      Execute(command: string, arguments: string, workingDirectory: string): wshcmx.Net.ProcessResult;
    }

    export abstract class ProcessResult {
      get_ExitCode(): number;
      get_StandardOutput(): string;
      get_StandardError(): string;
      get_StartTime(): Date;
      get_ExitTime(): Date;
      get_Duration(): number;
      get_IsSuccess(): boolean;
    }

    export abstract class Sql {
      Init(connectionString: string, databaseType: 0 | 1): void;
      Init(connectionString: string, databaseTypeNumber: number): void;
      ExecuteQuery(commandText: string): { Key: string; Value: unknown }[][];
      ExecuteNonQuery(commandText: string): void;
      ExecutePaginationProcedure(procedureName: string, serializedOptions: string, serializedParameters: string): unknown[];
      ExecuteProcedure(procedureName: string, serializedParameters: string): unknown[];
    }

    export abstract class Templater {
      Generate(template: string, data: unknown[]): string;
    }
  }
}
