// -------------------------------------------------------
// <auto-generated>
//    This file is generated by wshcmx/net project. Do not edit manually.
//    Generated on: 2026-05-15 15:36:10
// <auto-generated />
// -------------------------------------------------------

export namespace wshcmx {
  namespace Net {
    type KeyValuePair<K, V> = { Key: K; Value: V };

    export abstract class ProcessHelper {
      Execute(command: string, arguments?: string, workingDirectory?: string, timeoutMilliseconds?: number): wshcmx.Net.ProcessResult;
    }

    export abstract class ProcessResult {
      ExitCode: number;
      Completed: boolean;
      StandardOutput: string;
      StandardError: string;
      StartTime: Date;
      ExitTime: Date;
      Duration: number;
      IsSuccess: boolean;
    }

    export abstract class Sql {
      Init(connectionString: string, databaseType?: 0 | 1): void;
      Init(connectionString: string, databaseTypeNumber: number): void;
      ExecuteQuery(commandText: string): { Key: string; Value: unknown }[][];
      ExecuteNonQuery(commandText: string): void;
      ExecutePaginationProcedure(procedureName: string, serializedOptions: string, serializedParameters: string): unknown[];
      ExecuteProcedure(procedureName: string, serializedParameters: string): unknown[];
    }

    export abstract class Templater {
      Generate(template: string, data: unknown[]): string;
    }
  }
}
