// -------------------------------------------------------
// <auto-generated>
//    This file is generated by wshcmx/net project. Do not edit manually.
//    Generated on: 2025-05-27 20:50:41
// <auto-generated />
// -------------------------------------------------------

declare namespace wshcmx {
  namespace Net {
    type KeyValuePair<K, V> = { Key: K; Value: V };

    export abstract class Sql {
      Init(connectionString: string): void;
      ExecuteQuery(commandText: string): { Key: string; Value: unknown }[][];
      ExecuteNonQuery(commandText: string): void;
      ExecutePaginationProcedure(procedureName: string, serializedOptions: string, serializedParameters: string): unknown[];
      ExecuteProcedure(procedureName: string, serializedParameters: string): unknown[];
    }

    export abstract class Templater {
      Generate(template: string, data: unknown[]): string;
    }
  }
}
