using System.Reflection;
using System.Text;

namespace Typifier;

public static class Generator
{
    private const string NamespaceName = "wshcmx";
    private const string BuildPath = "src/Typifier/types/index.d.ts";

    public static void Generate()
    {
        string definitions = BuildDefinitions(Assembly.Load(NamespaceName), DateTime.Now);

        if (!Directory.Exists(Path.GetDirectoryName(BuildPath)))
        {
            Directory.CreateDirectory(Path.GetDirectoryName(BuildPath)!);
        }

        File.WriteAllText(BuildPath, definitions);
    }

    internal static string BuildDefinitions(Assembly assembly, DateTime generatedOn)
    {
        IEnumerable<Type> types = assembly
            .GetTypes()
            .Where(x =>
                !x.Name.EndsWith("Attribute") &&
                x.IsClass &&
                (x.IsPublic || x.IsNestedPublic) &&
                !x.Name.StartsWith("<"));

        StringBuilder sb = new();
        sb.AppendLine("// -------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"//    This file is generated by {NamespaceName}/net project. Do not edit manually.");
        sb.AppendLine($"//    Generated on: {generatedOn:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// -------------------------------------------------------");
        sb.AppendLine($"\ndeclare namespace {NamespaceName} {{");
        sb.AppendLine($"  namespace Net {{");
        sb.AppendLine($"    type KeyValuePair<K, V> = {{ Key: K; Value: V }};");

        foreach (Type type in types)
        {
            sb.AppendLine($"\n    export abstract class {type.Name} {{");

            foreach (var method in type.GetMethods(BindingFlags.Instance | BindingFlags.Public | BindingFlags.DeclaredOnly | BindingFlags.Static))
            {
                if (method.IsSpecialName)
                {
                    string propertyName = method.Name[4..];
                    var property = type.GetProperty(propertyName);

                    if (property != null)
                    {
                        sb.AppendLine($"      {propertyName}: {MapType(property.PropertyType)};");
                        continue;
                    }
                }
                List<string> parameters = [];
                ParameterInfo[] methodParameters = method.GetParameters();
                bool[] optionalParameters = GetOptionalParameters(methodParameters);

                for (int i = 0; i < methodParameters.Length; i++)
                {
                    ParameterInfo parameter = methodParameters[i];
                    string optionalMarker = optionalParameters[i] ? "?" : string.Empty;
                    parameters.Add($"{parameter.Name}{optionalMarker}: {MapType(parameter.ParameterType)}");
                }

                sb.AppendLine($"      {method.Name}({string.Join(", ", parameters)}): {MapType(method.ReturnType)};");
            }

            sb.AppendLine("    }");
        }

        sb.AppendLine("  }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string MapType(Type type)
    {
        if (type == typeof(void)) return "void";
        if (type == typeof(string)) return "string";
        if (type == typeof(bool)) return "boolean";
        if (type == typeof(int)) return "number";
        if (type == typeof(DateTime)) return "Date";
        if (type == typeof(long)) return "number";
        if (type.IsEnum)
        {
            string[] enumValues = Enum.GetValues(type)
                .Cast<object>()
                .Select(value => EnumValueToNumberLiteral(type, value))
                .Distinct()
                .ToArray();

            return enumValues.Length == 0 ? "number" : string.Join(" | ", enumValues);
        }
        if (type == typeof(object)) return "unknown";

        Type? possibleType = Nullable.GetUnderlyingType(type);

        if (possibleType != null)
        {
            return MapType(possibleType) + " | null";
        }

        // Handle jagged arays
        if (type.IsArray)
        {
            var elementType = type.GetElementType();

            if (elementType != null)
            {
                return MapType(elementType) + "[]";
            }
        }

        if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(List<>))
        {
            return MapType(type.GetGenericArguments()[0]) + "[]";
        }

        if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(KeyValuePair<,>))
        {
            return $"{{ Key: {MapType(type.GetGenericArguments()[0])}; Value: {MapType(type.GetGenericArguments()[1])} }}";
        }

        return type.ToString();
    }

    private static string EnumValueToNumberLiteral(Type enumType, object enumValue)
    {
        Type underlyingType = Enum.GetUnderlyingType(enumType);

        if (underlyingType == typeof(byte) || underlyingType == typeof(ushort) || underlyingType == typeof(uint) || underlyingType == typeof(ulong))
        {
            return Convert.ToUInt64(enumValue).ToString();
        }

        return Convert.ToInt64(enumValue).ToString();
    }

    private static bool[] GetOptionalParameters(IReadOnlyList<ParameterInfo> parameters)
    {
        bool[] optionalParameters = new bool[parameters.Count];
        bool canMarkOptional = true;

        for (int i = parameters.Count - 1; i >= 0; i--)
        {
            bool isOptional = parameters[i].IsOptional || parameters[i].HasDefaultValue;
            optionalParameters[i] = canMarkOptional && isOptional;

            if (!isOptional)
            {
                canMarkOptional = false;
            }
        }

        return optionalParameters;
    }
}
