name: Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: Publish
        run: dotnet publish src/wshcmx -f netstandard2.0 -r linux-x64 -c Release -o ./publish
      - name: Create ZIP
        run: cd ./publish && zip -r ../wshcmx-linux-x64.zip ./*
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: wshcmx-linux-x64
          path: wshcmx-linux-x64.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v7
        with:
          merge-multiple: true
          path: ./release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          name: Release ${{ github.event.release.tag_name }}
          body: "Automated release for ${{ github.event.release.tag_name }}."
          files: release/wshcmx-linux-x64.zip