name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        runtime: [ win-x64, linux-x64, osx-arm64 ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build for ${{ matrix.runtime }}
        run: dotnet build --configuration Release --no-restore
      - name: Run Tests
        run: dotnet test --configuration Release --no-build --verbosity normal
      - name: Publish Application
        run: dotnet publish src/wshcmx -r ${{ matrix.runtime }} -c Release -o ./publish/${{ matrix.runtime }}
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wshcmx-${{ matrix.runtime }}
          path: ./publish/${{ matrix.runtime }}
  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release/**/*.*
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
